- name: Get AWS account information
  local_action:
    module: aws_caller_facts
  register: caller_facts
  
- name: Check that instance is running
  local_action:
    module: ec2_instance_facts
    region: "{{ ec2_region }}"
    filters:
      "tag:Name": "{{ ec2_user }}-nfs-server"
      "tag:creator_arn": "{{ caller_facts.arn }}"
      "tag:user": "{{ ec2_user }}"
      "tag:creator": "ocp4-extender"
  register: ec2_instance

- name: Save instanse public ip
  set_fact:
    nfs_server_ip: "{{ (ec2_instance.instances | selectattr('state.name', 'equalto', 'running') | list )[0]['public_ip_address'] }}"
  
- name: Wait for SSH to be available on instance
  wait_for:
    host: "{{ nfs_server_ip }}"
    port: 22
    search_regex: OpenSSH
    delay: 10
    timeout: 300

- debug:
    var: nfs_server_ip
  