- hosts: localhost
  roles:
    - ocp3_aws_provision

# AWS group is created in previous role
- hosts: aws
  roles:
    - ocp3_aws_deploy

- hosts: localhost
  tasks:
    - include_role:
        name: ocp3_aws_deploy
        tasks_from: login
