- hosts: localhost
  tasks:
    - include_vars:
        file: "{{ playbook_dir }}/roles/ocp3_aws_deploy/defaults/main.yml"

    - include_role:
        name: ec2_provision
        tasks_from: get_ip
      vars:
        instance_name: "{{ aws_name_suffix }}"

    - name: Add host ssh settings
      add_host:
        name: "{{ ec2_instance_ip }}"
        ansible_user: ec2-user
        ansible_ssh_private_key_file: "{{ ec2_private_key_file }}"
        ansible_become: yes

    - name: Remove subscriptions from system
      redhat_subscription:
        state: absent
        username: "{{ sub_user }}"
        password: "{{ sub_pass }}"
      delegate_to: "{{ ec2_instance_ip }}"

    - include_role:
        name: ec2_provision
        tasks_from: destroy_instance
      vars:
        instance_name: "{{ aws_name_suffix }}"
  vars_files:
    - "{{ playbook_dir }}/config/defaults.yml"
