- hosts: localhost
  vars_files: "{{ playbook_dir }}/config/defaults.yml"
  tasks:
    - name: Clone the openshift-ansible repo
      git:
        repo: 'https://github.com/openshift/openshift-ansible'
        dest: "{{ workspace }}/openshift-ansible"
        version: "release-{{ (lookup('env', 'OPENSHIFT_VERSION') or 'v3.11')[1:] }}"
        force: yes

    - name: Creating a fake file for OCP-3.7
      lineinfile:
        path: "{{ workspace }}/openshift-ansible/playbooks/deploy_cluster.yml"
        create: yes
        line: "- hosts: localhost"
      when: ocp_version == "v3.7"

    - name: Creating a fake file for OCP-3.11
      lineinfile:
        path: "{{ workspace }}/openshift-ansible/playbooks/byo/config.yml"
        create: yes
        line: "- hosts: localhost"
      when: ocp_version == "v3.11"
