---
- name: Extract nfs server ip
  hosts: localhost
  roles:
    - nfs_deploy

- name: Add OCP EC2 instance host to in memory inventory
  hosts: localhost
  tasks:
    - add_host:
        name: "{{ nfs_server_ip }}"
        group: ocp_nfs_servers
        ansible_user: "{{ ec2_user }}"
        ansible_ssh_private_key_file: "{{ ec2_private_key_file }}"
  vars:
    ec2_user: "ec2-user"
    ec2_private_key_file: "../keys/ci.pem"
  tags:
    - always

- name: Setup OCP NFS storage
  hosts: ocp_nfs_servers
  tasks:
  vars:
    ansible_ssh_common_args: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
  roles:
    - nfs_config
  environment:
    PATH: "{{ ansible_env.PATH }}:~/bin"

- name: Provision the PVs on the cluster
  hosts: localhost
  roles:
    - nfs_provision
