- include_vars:
    file: "{{ playbook_dir }}/config/defaults.yml"

- include_vars:
    file: "{{ playbook_dir }}/roles/ocp3_aws_deploy/defaults/main.yml"

- include_tasks: aws_instance_provision.yml

- include_tasks: add_oa_host_inventory.yml
