- include_vars:
    file: "{{ playbook_dir }}/config/defaults.yml"

- include_vars:
    file: "{{ playbook_dir }}/roles/ocp3_aws_deploy/defaults/main.yml"

- name: Get AWS EC2 instance ip
  include_role:
    name: ec2_provision
    tasks_from: get_ip
  vars:
    instance_name: "{{ aws_name_suffix }}"

- name: Login to cluster
  include_role:
    name: login_ocp
  vars:
    force_login: true
    kubeconfig: "{{ source_kubeconfig }}"
    console_addr: "https://{{ ec2_instance_ip }}.nip.io:8443"
