- name: Include common variables
  include_vars:
    file: "{{ playbook_dir }}/config/defaults.yml"

- name: Provision an AWS EC2 instance
  include_role:
    name: ec2_provision
    tasks_from: provision_instance
  vars:
    instance_name: "{{ aws_name_suffix }}"
    instance_type: t2.xlarge
    rhel_version: '7.5'
    security_group_type: ocp3

- name: Get AWS EC2 instance ip
  include_role:
    name: ec2_provision
    tasks_from: get_ip
  vars:
    instance_name: "{{ aws_name_suffix }}"

- name: Add target EC2 host ip to group aws
  add_host:
    groups: "aws"
    name: "{{ ec2_instance_ip }}"
    ansible_user: ec2-user
    ansible_ssh_private_key_file: "{{ ec2_private_key_file }}"
    ansible_become: yes

- name: Add openshift all-in-one inventory
  add_host:
    name: "{{ ec2_instance_ip }}.xip.io"
    groups:
      - masters
      - nodes
      - OSEv3
      - etcd
      # - nfs
    ansible_become: yes
    ansible_user: ec2-user
    ansible_ssh_private_key_file: "{{ ec2_private_key_file }}"
    # ansible_service_broker_log_level: debug
    # ansible_service_broker_output_request: true
    # ansible_service_broker_registry_url: "http://asb-registry.usersys.redhat.com:5000"
    # ansible_service_broker_registry_name: dh
    # ansible_service_broker_registry_tag: "v{{ ocp_version }}"
    # ansible_service_broker_image_prefix: "asb-registry.usersys.redhat.com:5001/openshift3/ose-"
    # ansible_service_broker_image_tag: "v{{ ocp_version }}"
    # openshift_examples_registryurl: registry.redhat.io
    # openshift_examples_modify_imagestreams: true
    # openshift_examples_load_centos: false
    # openshift_examples_load_rhel: true
    # openshift_use_system_containers: true
    os_sdn_network_plugin_name: 'redhat/openshift-ovs-multitenant'
    # ansible_service_broker_install: true
    openshift_deployment_type: origin
    openshift_disable_check: 'disk_availability,memory_availability,docker_storage'
    # openshift_docker_additional_registries:
    #   - 'asb-registry.usersys.redhat.com:5001'
    # openshift_docker_insecure_registries:
    #   - 'asb-registry.usersys.redhat.com:5000'
    # oreg_url: "asb-registry.usersys.redhat.com:5001/openshift3/ose-${component}:v{{ ocp_version }}"
    # system_images_registry: asb-registry.usersys.redhat.com:5001
    # openshift_enable_service_catalog: true
    # openshift_hosted_etcd_storage_kind: nfs
    # openshift_hosted_etcd_storage_nfs_options: "*(rw,root_squash,sync,no_wdelay)"
    # openshift_hosted_etcd_storage_nfs_directory: /var/lib/exports
    # openshift_hosted_etcd_storage_volume_name: etcd
    # openshift_hosted_etcd_storage_access_modes:
    #   - ReadWriteOnce
    # openshift_hosted_etcd_storage_volume_size: 10G
    # openshift_hosted_etcd_storage_labels:
    #   storage: etcd
    openshift_public_hostname: "{{ ec2_instance_ip }}.xip.io"
    openshift_public_ip: "{{ ec2_instance_ip }}"
    openshift_master_cluster_public_hostname: "{{ ec2_instance_ip }}.xip.io"
    openshift_master_default_subdomain: "apps.{{ ec2_instance_ip }}.xip.io"
    openshift_master_identity_providers:
      - name: allow_all
        login: true
        challenge: true
        kind: AllowAllPasswordIdentityProvider
    openshift_schedulable: true
    # openshift_service_catalog_image_prefix: "asb-registry.usersys.redhat.com:5001/openshift3/ose-"
    os_update: true
    openshift_release: "{{ ocp_version }}"
    openshift_portal_net: 172.30.0.0/16
    openshift_image_tag: "v{{ ocp_version }}"
    # template_service_broker_prefix: "asb-registry.usersys.redhat.com:5001/openshift3/ose-"
    # template_service_broker_version: "v{{ ocp_version }}"
    # openshift_web_console_image: "asb-registry.usersys.redhat.com:5001/openshift3/ose-web-console:v{{ ocp_version }}"
    # openshift_cockpit_deployer_image: "asb-registry.usersys.redhat.com:5001/openshift3/ose-deployer:v{{ ocp_version }}"
    openshift_node_groups:
    - name: 'node-config-all-in-one'
      labels:
      - 'node-role.kubernetes.io/master=true'
      - 'node-role.kubernetes.io/infra=true'
      - 'node-role.kubernetes.io/compute=true'
    openshift_node_group_name: "node-config-all-in-one"
    # osm_use_cockpit: false
    # openshift_cluster_monitoring_operator_install: false
    #openshift_use_crio: true
    #openshift_crio_systemcontainer_image_override: asb-registry.usersys.redhat.com:5001/openshift3/cri-o:v{{ ocp_version }}

# - name: fix node template?
#   shell: sed -i "s/dnsIP.*$/dnsIP{{ ':' }} {{ ec2_instance_ip }}/g" roles/openshift_node_group/templates/node-config.yaml.j2
#   args:
#     chdir: /home/dgrigore/Documents/work/openshift/openshift-ansible
