- name: ensure kubeconfigs directory was created
  file:
    state: directory
    path: "{{ target_kubeconfig | dirname }}"

- name: copy kubeconfig to specified location
  copy:
    src: "{{ source_kubeconfig }}"
    dest: "{{ target_kubeconfig }}"
    remote_src: true

- debug:
    msg: "Now {{ target_kubeconfig }} is containing {{ source_kubeconfig }}"
