- name: Ensure copy location dir was created
  file:
    state: directory
    recurse: true
    path: "{{ copy_location | dirname }}"

- name: copy kubeconfig to specified location
  copy:
    src: "{{ kubeconfig }}"
    dest: "{{ copy_location }}"
    remote_src: true

- debug:
    msg: "Backup of '{{ kubeconfig }}' is stored in '{{ copy_location }}'"
