- debug:
    msg: "Logging into cluster using KUBECONFIG: {{ source_kubeconfig }}"

- name: login to cluster
  shell: "{{ oc_binary_location }}/oc login -u {{ user }} -p {{ pass }} --insecure-skip-tls-verify=true"
  register: login
  retries: 10
  delay: 6
  until: login.rc == 0
  environment:
    KUBECONFIG: "{{ source_kubeconfig }}"
