- name: Login to cluster
  shell: "{{ oc_binary }} login -u {{ user }} -p {{ passwd }} {{ console_addr }} --insecure-skip-tls-verify=true"
  register: login
  retries: 10
  delay: 6
  until: login.rc == 0
  environment:
    KUBECONFIG: "{{ source_kubeconfig }}"
