---
- debug:
    msg: "Logging into cluster using KUBECONFIG: {{ ansible_env.KUBECONFIG }}"

- name: login to cluster
  vars:
    kubeadmin_password: "{{ lookup('file', '{{ playbook_dir }}/auth/kubeadmin-password') }}"
  shell: "{{ oc_binary_location }}/oc login -u {{ user }} -p {{ kubeadmin_password }}"

- name: dump cluster token to auth/kube-token
  shell: "oc whoami -t > {{ playbook_dir }}/auth/kube-token"
