---
- debug:
    msg: "Logging into cluster using KUBECONFIG: {{ ansible_env.KUBECONFIG }}"

- name: login to cluster
  vars:
    kubeadmin_password: "{{ lookup('file', '{{ playbook_dir }}/auth/kubeadmin-password') }}"
  shell: "{{ oc_binary_location }}/oc login -u {{ user }} -p {{ kubeadmin_password }}"
  register: login
  retries: 10
  delay: 6
  until: login.rc == 0
