---
# Credentials for oc login
user: admin # Username for cluster login
passwd: admin # Password for cluster login
console_addr: '' # User specified cluster address
force_login: false # Login into cluster anyway with provided credentials

# Kubeconfig processing
kubeconfig: "{{ lookup('env', 'KUBECONFIG') or '~/.kube/config' }}"
copy_location: ""

# Download section
system_types:
  "Darwin": "mac"
ocp_release_extension:
  'linux': 'tar.gz'
  'mac': 'zip'
system_prefix: "{{ system_types[ansible_os_family] | default('linux') }}"
oc_target_location: "{{ oc_binary | dirname }}"
release_url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest
