openshift_installer_release: "v0.15.0"
openshift_installer_release_type: "linux"
openshift_installer_release_url: "https://github.com/openshift/installer/releases/download/{{ openshift_installer_release }}/openshift-install-{{ openshift_installer_release_type }}-amd64"
