openshift_installer_release: "{{ lookup('env', 'OCP4_RELEASE') or 'latest' }}"
openshift_installer_release_type: "linux"
openshift_installer_release_url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ openshift_installer_release }}/openshift-install-{{ openshift_installer_release_type }}-{{ openshift_installer_release }}.tar.gz"
ocp4_admin_user:  "{{ lookup('env', 'OCP4_ADMIN_USER') or 'admin' }}"
ocp4_admin_password:  "{{ lookup('env', 'OCP4_ADMIN_PASSWD') or 'r3dh4t1!' }}"
ocp4_htpasswd_file: "{{ playbook_dir }}/ocp4-htpasswd"
openshift_installer_release_prefix_url: "https://mirror.openshift.com/pub/openshift-v4/clients/"
openshift_parent_dir_choices: { latest-4.1: 'ocp', latest-4.2: 'ocp', latest: 'ocp', nightly: 'ocp-dev-preview' }
openshift_parent_subdir_choices: { latest-4.1: 'latest-4.1', latest-4.2: 'latest-4.2', latest: 'latest', nightly: 'latest' }
openshift_installer_regex_choices: { latest-4.1: '\d[-.0-9]+\d', latest-4.2: '\d[-.0-9]+\d', latest: '\d[-.0-9]+\d', nightly: '\d[-.0-9]+\.nightly-[-.0-9]+\d' }
