- include_role:
    name: ec2_provision
    tasks_from: get_ip
  vars:
    instance_name: "{{ aws_name_suffix }}"
    skip_ssh_check: true

- name: Add host ssh settings
  add_host:
    name: "{{ ec2_instance_ip }}"
    ansible_user: ec2-user
    ansible_ssh_private_key_file: "{{ ec2_private_key_file }}"
    ansible_become: true

- block:
  - name: "Destroy OA {{ ocp3_version }} cluster"
    shell: ansible-playbook /var/tmp/mig-ci/aws_playbooks/destroy_aws.yml > /var/tmp/.uninstall.log
    async: 1200
    poll: 0
    register: task

  - name: Check OA {{ ocp3_version }} destroy status
    async_status:
      jid: "{{ task.ansible_job_id }}"
    register: destroy
    until: destroy.finished
    retries: 60
    delay: 20
  delegate_to: "{{ ec2_instance_ip }}"
