- name: "Fetch OCP4 {{ openshift_installer_release }} release content"
  uri:
    url: "{{ openshift_installer_release_prefix_url }}/{{ openshift_parent_dir_choices[openshift_installer_release] }}/{{ openshift_parent_subdir_choices[openshift_installer_release] }}"
    return_content: yes
  register: page
  until: page is success
  retries: 15
  delay: 10

- name: "Determine OCP4 {{ openshift_installer_release }} installer release"
  set_fact:
    installer_latest_release: "{{ page.content | regex_findall('<a.*openshift-install[^<]+?>') | last | regex_search(openshift_installer_regex_choices[openshift_installer_release]) }}"

- name: "Determine OCP4 {{ openshift_installer_release }} client release"
  set_fact:
    client_latest_release: "{{ page.content | regex_findall('<a.*openshift-client[^<]+?>') | last | regex_search(openshift_installer_regex_choices[openshift_installer_release]) }}"

- name: "Set variables to OCP4 {{ openshift_installer_release }} release"
  set_fact:
    openshift_installer_release_url: "{{ openshift_installer_release_prefix_url }}/{{ openshift_parent_dir_choices[openshift_installer_release] }}/{{ openshift_parent_subdir_choices[openshift_installer_release] }}/openshift-install-linux-{{ installer_latest_release }}.tar.gz"
    openshift_client_release_url: "{{ openshift_installer_release_prefix_url }}/{{ openshift_parent_dir_choices[openshift_installer_release] }}/{{ openshift_parent_subdir_choices[openshift_installer_release] }}/openshift-client-linux-{{ client_latest_release }}.tar.gz"

- debug:
    msg: 
    - "OCP4 {{ openshift_installer_release }} installer release : {{ openshift_installer_release_url }}"
    - "OCP4 {{ openshift_installer_release }} client release : {{ openshift_client_release_url }}"

- name: "Write {{ openshift_installer_release }} release to ocp4_release.yml"
  template:
    src: ocp4_release.yml.j2
    dest: "{{ playbook_dir }}/ocp4_release.yml"
