---
- name: "Gather details for using {{ openshift_installer_release }} release"
  block:

    - name: "Set URL for {{ openshift_installer_release }} release"
      set_fact:
        openshift_installer_dynamic_url: "{{ openshift_installer_release_prefix_url }}/{{ openshift_parent_dir_choices[openshift_installer_release] }}/{{ openshift_parent_subdir_choices[openshift_installer_release] }}"

    - name: "Fetch {{ openshift_installer_release }} release content"
      uri:
        url: "{{ openshift_installer_dynamic_url }}"
        return_content: yes
      register: page
      until: page is success
      retries: 12
      delay: 10

    - name: "Determine {{ openshift_installer_release }} installer release"
      set_fact:
        latest_release: "{{ page.content | regex_findall('<a.*openshift-install[^<]+?>') | last | regex_search(openshift_installer_regex_choices[openshift_installer_release]) }}"

    - name: "Set variables to {{ latest_release }} release"
      set_fact:
        openshift_installer_release: "{{ latest_release }}"
        openshift_installer_release_url: "{{ openshift_installer_dynamic_url }}/openshift-install-{{ openshift_installer_release_type }}-{{ latest_release }}.tar.gz"

  when: openshift_installer_release == "latest-4.1" or openshift_installer_release == "latest-4.2" or openshift_installer_release == "latest" or openshift_installer_release == "nightly"

- name: Get OCP4 installer
  unarchive:
    src: "{{ openshift_installer_release_url }}"
    dest: "{{ playbook_dir }}"
    mode: 0775
    remote_src: true
  register: get_installer
  until: get_installer is success
  retries: 12
  delay: 10
