---
- name: "Discover available nightly installer releases"
  uri:
    url: "{{ openshift_installer_nightly_release_url_prefix }}"
    return_content: yes
  register: latest_nightly_page

- name: "Determine latest nightly installer release"
  set_fact:
    latest_nightly: "{{ latest_nightly_page.content | regex_findall('\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}-\\d{1,3}\\.nightly-\\d{4}-\\d{2}-\\d{2}-\\d{6}') | last  }}"

- name: "Set variables to {{ latest_nightly }} release"
  set_fact:
    openshift_installer_release: "{{ latest_nightly }}"
    openshift_installer_release_url: "{{ openshift_installer_nightly_release_url_prefix }}/{{ latest_nightly }}/openshift-install-{{ openshift_installer_release_type }}-{{ latest_nightly }}.tar.gz"
