- name: Check if mig operator repo exists
  stat:
    path: "{{ mig_operator_location }}"
  register: op_repo

- name: Clone the mig operator repo
  git:
    dest: "{{ mig_operator_location }}"
    repo: "{{ mig_operator_repo }}"
    version: "{{ mig_operator_branch }}"
  ignore_errors: true
  when: not op_repo.stat.exists

- debug:
    msg: "Mig operator will deploy using release : {{ mig_operator_tag }}"

- name: Deploy mig operator
  k8s:
    state : present
    definition: "{{ lookup('file', '{{ mig_operator_location }}/deploy/non-olm/{{ mig_operator_tag }}/operator.yml' )}}"

- name: Check status of mig operator
  k8s_facts:
    kind: Pod
    namespace: "{{ mig_migration_namespace }}"
    label_selectors: "app=migration-operator"
  register: pod
  until: "true in (pod | json_query('resources[].status.containerStatuses[].ready'))"
  retries: 60
  delay: 10
