- name: Clone the mig operator repo
  git:
    dest: "{{ mig_operator_location }}"
    repo: "{{ mig_operator_repo }}"
    version: "{{ mig_operator_branch }}"
  ignore_errors: true

- name: Update operator to use {{ mig_operator_tag }} tag
  replace:
    path: "{{ mig_operator_location }}/operator.yml"
    backup: yes
    regexp: '^(.*?)image:(.*)'
    replace: '\1image: {{ mig_operator_img }}:{{ mig_operator_tag }}'

- debug:
    msg: "Mig operator will deploy using {{ mig_operator_img }}:{{ mig_operator_tag }}"

- name: Deploy mig operator
  k8s:
    state : present
    definition: "{{ lookup('file', '{{ mig_operator_location }}/operator.yml' )}}"

- name: Check status of mig operator
  k8s_facts:
    kind: Pod
    namespace: "{{ mig_migration_namespace }}"
    label_selectors: "app=migration-operator"
  register: pod
  until: "true in (pod | json_query('resources[].status.containerStatuses[].ready'))"
  retries: 60
  delay: 10
