---
# OCP3 host clusters login to OCP4 for remote cluster tasks, the opposite for OCP4 host clusters.

- name: Logging to OCP4 and saving credentials
  include_role:
    name: login_ocp
  vars:
    source_kubeconfig: "{{ playbook_dir }}/auth/kubeconfig"
    target_kubeconfig: "{{ ocp4_kubeconfig }}"
  when: cluster_version == '3'

- name: Logging to OCP3 and saving credentials
  include_role:
    name: login_ocp
  vars:
    source_kubeconfig: "{{ playbook_dir }}/kubeconfigs/kubeconfig"
    target_kubeconfig: "{{ ocp3_kubeconfig }}"
  when: cluster_version == '4'

- set_fact:
    remote_cluster_kubeconfig: "{{ ocp4_kubeconfig }}"
  when: cluster_version == '3'

- set_fact:
    remote_cluster_kubeconfig: "{{ ocp3_kubeconfig }}"
  when: cluster_version == '4'

- name: Start remote cluster tasks
  block:

    - name: Extract SA token
      shell: "{{ oc_binary }} sa get-token -n {{ mig_controller_namespace }} {{ mig_controller_sa_name }} | base64 -w 0"
      register: oc_sa_output

    - set_fact:
        sa_token: "{{ oc_sa_output.stdout }}"

     # Fix me: need to find a better way to obtain the master API url from k8s_facts
     # Current context always returns only one entry 

    - name: Extract cluster URL from current context
      shell: "{{ oc_binary }} status | head -1 | sed -E 's/^.* (https:.*)/\\1/'"
      register: oc_config_output

    - set_fact:
       dest_cluster_url: "{{ oc_config_output.stdout }}"

    - debug:
        msg: "Destination cluster URL set to: {{ dest_cluster_url }}"

  environment:
    KUBECONFIG: "{{ remote_cluster_kubeconfig }}"
