- name: Get AWS account information
  local_action:
    module: aws_caller_facts
  register: caller_facts

- set_fact:
    aws_resource_tag: "{{ prefix + instance_name + caller_facts.arn | hash('md5') }}"

- ec2_instance_facts:
    filters:
      "tag:Name": "{{ prefix }}-{{ instance_name }}"
      "tag:creator": "{{ aws_resource_tag }}"
  register: ec2_metadata

- block:
  - set_fact:
      instances: "{{ ec2_metadata.instances | map(attribute='instance_id') | list }}"

  - debug:
      msg:
      - "These instances will be terminated"
      - "{{ instances }}"

  - local_action:
      module: ec2
      instance_ids: "{{ instances }}"
      state: absent
      wait: true
  ignore_errors: true

