- name: Get AWS account information
  local_action:
    module: aws_caller_facts
  register: caller_facts

- name: Get instance info
  local_action:
    module: ec2_instance_facts
    region: "{{ ec2_region }}"
    filters:
      "tag:Name": "{{ ansible_user }}-{{ instance_name }}"
      "tag:creator_arn": "{{ caller_facts.arn }}"
      "tag:user": "{{ ansible_user }}"
  register: ec2_instance

- name: Get instance public ip
  set_fact:
    ec2_instance_ip: "{{ (ec2_instance.instances | selectattr('state.name', 'match', '^running$') | list )[0]['public_ip_address'] }}"

- name: Wait for SSH to be available on instance
  wait_for:
    host: "{{ ec2_instance_ip }}"
    port: 22
    search_regex: OpenSSH
    delay: 10
    timeout: 900

- debug:
    var: ec2_instance_ip
