- name: Get AWS account information
  local_action:
    module: aws_caller_facts
  register: caller_facts

- set_fact:
    aws_resource_tag: "{{ prefix + instance_name + caller_facts.arn | hash('md5') }}"

- name: Get instance info
  local_action:
    module: ec2_instance_facts
    filters:
      "tag:Name": "{{ prefix }}-{{ instance_name }}"
      "tag:creator": "{{ aws_resource_tag }}"
  register: ec2_instance

- name: Select instance
  set_fact:
    instance: "{{ (ec2_instance.instances | selectattr('state.name', 'match', '^running$') | list )[0] }}"

- name: Get instance public ip
  set_fact:
    ec2_instance_ip: "{{ instance['public_ip_address'] }}"

- name: Wait for SSH to be available on instance
  wait_for:
    host: "{{ ec2_instance_ip }}"
    port: 22
    search_regex: OpenSSH
    delay: 20
    timeout: 300
  register: result
  until: result is succeeded
  retries: 5
  when: skip_ssh_check | default(false) | bool == false

- debug:
    var: ec2_instance_ip
