- name: Check that velero_aws_credentials were created
  stat:
    path: "{{ playbook_dir }}/config/velero_aws_creds.yml"
  register: creds

- name: Destroy S3 bucket if present
  block:

    - name: Get bucket info
      include_vars:
        file: "{{ playbook_dir }}/config/velero_aws_creds.yml"

    - name: Get AWS account information
      aws_caller_facts:
      register: caller_facts

    - name: Retrieve AWS account identifier (ARN) for use in resource tags
      set_fact:
        aws_account_arn: "{{ caller_facts.arn }}"

    - debug:
        msg: "Will destroy s3 bucket : {{ velero_aws_bucket_name }}"

    - name: Delete S3 bucket for backup storage of OpenShift resource definitions
      s3_bucket:
        state: absent
        force: true
        name: "{{ velero_aws_bucket_name }}"
        region: "{{ ec2_region }}"
        tags:
          owner: "{{ aws_account_arn }}"
      ignore_errors: true

    - name: Remove old aws backup storage access keys
      file:
        path: "{{ playbook_dir }}/config/velero_aws_creds.yml"
        state: absent
  when: creds.stat.exists
