---
- name: Include required vars
  include_vars:
    file: "{{ playbook_dir }}/roles/mig_controller_prereqs/defaults/main.yml"

- name: Destroy migration namespace
  k8s:
    state: absent
    api_version: v1
    kind: Namespace
    name: "{{ mig_migration_namespace }}"
    wait: yes
    wait_timeout: 300

- name: Destroy velero CRDs
  k8s:
    state: absent
    api_version: v1beta1
    kind: CustomResourceDefinition
    name: "{{ item }}"
    wait: yes
  with_items: "{{ velero_crds }}"
