# default common variables for mig-ci roles/plays

# Jenkins WORKSPACE or assume parent dir
workspace: "{{ lookup('env', 'WORKSPACE') or '../'}}"

# AWS / EC2 related
aws_access_key_id: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
aws_secret_access_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
ec2_key: "{{ lookup('ENV', 'EC2_KEY') or 'ci' }}"
ec2_private_key_file: "{{ workspace }}/keys/{{ ec2_key }}.pem"
ec2_ssh_user: "ec2-user"
cluster_version: "{{ lookup('env', 'CLUSTER_VERSION') or '4'}}"
cluster_name: "{{ lookup('env', 'CLUSTER_NAME') or 'jenkins-ci'}}"
oc_binary_location: "{{ ansible_env.HOME }}/bin/"
ocp3_kubeconfig: "{{ ansible_env.HOME }}/kubeconfigs/ocp3-kubeconfig"
ocp4_kubeconfig: "{{ ansible_env.HOME }}/kubeconfigs/ocp4-kubeconfig"
