# default common variables for mig-ci roles/plays

# Jenkins WORKSPACE or assume parent dir
ec2_key: "{{ lookup('ENV', 'EC2_KEY') or 'ci' }}"
workspace: "{{ lookup('env', 'WORKSPACE') or '../'}}"
ec2_private_key_file: "{{ workspace }}/keys/{{ ec2_key }}.pem"
ec2_ssh_user: "ec2-user"
ec2_region: "{{ lookup('env', 'EC2_REGION') or 'us-east-2' }}"
cluster_version: "{{ lookup('env', 'CLUSTER_VERSION') or '4'}}"
