- name: Obtain NFS instance IP
  import_role:
    name: nfs_deploy
    tasks_from: get_ip

- name: Remove existing PVs
  shell: "for i in $(oc get pv --no-headers | awk '{ print $1 }'); do oc delete pv $i; done"

- name: Template the PV resources
  template:
    src: "pv.yml.j2"
    dest: "{{ role_path }}/files/pv.yml"

- name: Create NFS PVs
  shell: "oc create -f {{ role_path }}/files/pv.yml"

- name: Remove template tmp file
  file:
    state: absent
    path: "{{ role_path }}/files/pv.yml"
