- name: create velero dir
  file:
    path: "{{ playbook_dir }}/velero"
    state: directory

- name: get velero
  unarchive:
    src: "{{ velero_release_url }}"
    dest: "{{ playbook_dir }}/velero"
    remote_src: yes
