- name: Get client binary for Linux
  unarchive:
    remote_src: true
    src: "https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz"
    dest: "{{ oc_binary_location }}"
    mode: 0755
    
- name: Copy oc binary 
  copy: 
    src: "{{ oc_binary_location }}/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit/oc"
    dest: "{{ oc_binary_location }}/oc"
    remote_src: True  
