- name: Check status of mig controller
  k8s_facts:
    kind: Pod
    namespace: "{{ mig_controller_namespace }}"
    label_selectors: "control-plane=controller-manager"
  register: pod
  until: "true in (pod | json_query('resources[].status.containerStatuses[].ready'))"
  retries: 10
  delay: 15
