- debug:
    msg: "Mig controller will deploy using release: {{ mig_operator_release }}"

- name: Deploying mig controller using OLM
  block:

    - name: Include required vars
      include_vars:  "{{ lookup('first_found', olm_files) }}"
      vars:
        olm_files:
          - "{{ playbook_dir }}/olm/olm_vars.yml"
          - "{{ playbook_dir }}/roles/mig_controller_deploy/defaults/olm_vars.yml"
    
    - debug:
        msg: "OLM cluster version: {{ olm_cluster_version }}"

  when: mig_operator_use_olm|bool
    
- name: Deploy mig controller
  k8s:
    state: present
    definition: "{{ lookup('template', 'controller.yml.j2') }}"

- include: check.yml
