- debug:
    msg: "Mig controller will deploy using {{ mig_controller_img }}:{{ mig_controller_version }}"

- name: Deploy mig controller
  k8s:
    state: present
    definition: "{{ lookup('template', 'controller.yml.j2') }}"

- include: check.yml
