---

- name: Include required vars
  include_vars:
    file: "{{ item }}"
  with_items:
    - "{{ playbook_dir }}/roles/mig_controller_prereqs/defaults/main.yml"
    - "{{ playbook_dir }}/config/velero_aws_creds.yml"

- name: Deploy mig controller
  import_tasks: deploy.yml
  when: with_controller

- name: Process mig controller deployment summary
  import_tasks: summary.yml
