- name: install nfs-utils
  package:
    name: nfs-utils
    state: latest
  become: true

- name: create exports file
  copy:
    content: |
             /var/lib/nfs/exports *(rw,no_root_squash)
    dest: /etc/exports
  become: true

- name: Create pv dirs
  file:
    path: "/var/lib/nfs/exports/pv{{ item }}"
    state: directory
    mode: 0777
  with_sequence: start=1 end=9 
  become: true

- name: Start and enable nfs-server
  systemd:
    name: nfs-server
    state: started
    enabled: true
  become: true
